# Generated by Django 4.2.4 on 2023-12-23 21:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("healthcare_professional", "Healthcare Professional"),
                            ("administrator", "Administrator"),
                            ("patient", "Patient"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_admin",
                        to="account.account",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True, related_name="hospital_staff", to="account.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("address", models.TextField()),
                (
                    "nationality",
                    django_countries.fields.CountryField(max_length=2, null=True),
                ),
                (
                    "patient_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "nhis_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "file_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "emergency_contact_email",
                    models.EmailField(max_length=254, unique=True),
                ),
                ("emergency_contact_mobile", models.CharField(max_length=15)),
                (
                    "height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("genotype", models.CharField(blank=True, max_length=5)),
                ("date_of_open_file", models.DateField(auto_now_add=True)),
                ("barcode", models.ImageField(blank=True, upload_to="barcodes/")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("MD", "Doctor of Medicine"),
                            ("DO", "Doctor of Osteopathic Medicine"),
                            ("MBBS", "Bachelor of Medicine, Bachelor of Surgery"),
                            ("MS", "Master of Surgery"),
                            ("DNP", "Doctor of Nursing Practice"),
                            ("PhD", "Doctor of Philosophy in Medical Science"),
                            ("DPM", "Doctor of Podiatric Medicine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("specialization", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.hospital",
                    ),
                ),
            ],
        ),
    ]
