# Generated by Django 4.2.4 on 2023-12-23 21:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_started", models.DateField()),
                ("date_ended", models.DateField()),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("added", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("medical_condition", models.TextField()),
                ("medications", models.TextField()),
                (
                    "disease",
                    models.CharField(
                        choices=[
                            ("CVD", "Cardiovascular Disease"),
                            ("DIAB", "Diabetes"),
                            ("CANC", "Cancer"),
                            ("INF", "Infectious Disease"),
                            ("NEURO", "Neurological Disorder"),
                            ("RESPIR", "Respiratory Disorder"),
                            ("GI", "Gastrointestinal Disease"),
                            ("ORTH", "Orthopedic Condition"),
                            ("MENTAL", "Mental Health Disorder"),
                            ("ENDO", "Endocrine Disorder"),
                            ("RENAL", "Renal Disease"),
                            ("HEMATO", "Hematological Disorder"),
                            ("AUTOIMMUNE", "Autoimmune Disorder"),
                            ("DERMA", "Dermatological Condition"),
                            ("ALLERGIC", "Allergic Reaction"),
                            ("GENETIC", "Genetic Disorder"),
                            ("EYE", "Eye Disease"),
                            ("EAR", "Ear, Nose, and Throat Disorder"),
                            ("OBGYN", "Obstetric and Gynecological Condition"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField()),
                ("test_name", models.CharField(max_length=255)),
                ("result", models.TextField()),
                ("reference_range", models.CharField(max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("history_of_present_illness", models.TextField()),
                ("physical_examination", models.TextField()),
                ("assessment_and_plan", models.TextField()),
                ("orders_and_prescriptions", models.TextField()),
                ("progress_note", models.TextField()),
                ("findings", models.TextField()),
                (
                    "disease",
                    models.CharField(
                        choices=[
                            ("CVD", "Cardiovascular Disease"),
                            ("DIAB", "Diabetes"),
                            ("CANC", "Cancer"),
                            ("INF", "Infectious Disease"),
                            ("NEURO", "Neurological Disorder"),
                            ("RESPIR", "Respiratory Disorder"),
                            ("GI", "Gastrointestinal Disease"),
                            ("ORTH", "Orthopedic Condition"),
                            ("MENTAL", "Mental Health Disorder"),
                            ("ENDO", "Endocrine Disorder"),
                            ("RENAL", "Renal Disease"),
                            ("HEMATO", "Hematological Disorder"),
                            ("AUTOIMMUNE", "Autoimmune Disorder"),
                            ("DERMA", "Dermatological Condition"),
                            ("ALLERGIC", "Allergic Reaction"),
                            ("GENETIC", "Genetic Disorder"),
                            ("EYE", "Eye Disease"),
                            ("EAR", "Ear, Nose, and Throat Disorder"),
                            ("OBGYN", "Obstetric and Gynecological Condition"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "examiner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examinations",
                        to="account.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("data_access", "Data Access"),
                            ("modification", "Modification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("scheduled_time", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.patient",
                    ),
                ),
            ],
        ),
    ]
