# Generated by Django 4.2.4 on 2023-12-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.patient",
            ),
        ),
    ]
